Added description to all values of the SellerCloudPackageType enum.
SellerCloudTeam/SellerCloud.Core pull request #24
Opened 2020-10-01 06:34 UTC by DimitarChobanovSellerCloud

2020-10-01 06:39 UTC, StanislavChankovSellerCloud approved these changes
Thanks @DimitarChobanovSellerCloud

2020-10-01 06:55 UTC, stanimirsellercloud commented on src/SellerCloud.Core/Enums/PackageType/PackageType.cs
> +        [Description("Usps Flat Rate Padded Envelope")]
Please make sure the description used here matches what ShipBridge/CWA use. @MaxPower-tsvetkov-k can help if needed.

For example, in SB/CWA (and regular branded material), `USPS` is spelt all-uppercase.

2020-10-01 06:56 UTC, stanimirsellercloud commented on src/SellerCloud.Core/Enums/PackageType/PackageType.cs
> +        [Description("Usps Medium Flat Rate Box")]
I think the flat rate boxes do not have the `USPS` prefix. Please check in ShipBridge. It is possible that other packaging types have slightly different naming also.

2020-10-01 06:56 UTC, stanimirsellercloud commented on src/SellerCloud.Core/Enums/PackageType/PackageType.cs
> +        [Description("FedEx Your Packaging")]
Similarly, `Your Packaging` is used without the `FedEx` prefix.

2020-10-01 06:58 UTC, stanimirsellercloud requested changes
We should ensure that all the packaging types defined in `Core` have corresponding values as expected by ShipBridge and CWA.

These string values are set by plugins also, so they must match exactly (casing, hyphens, with/without prefixes where needed).

2020-10-01 13:51 UTC, zdravko-g approved these changes

2020-10-02 09:55 UTC, DimitarChobanovSellerCloud commented on src/SellerCloud.Core/Enums/PackageType/PackageType.cs
> +        [Description("FedEx Your Packaging")]
done

2020-10-02 09:55 UTC, DimitarChobanovSellerCloud commented on src/SellerCloud.Core/Enums/PackageType/PackageType.cs
> +        [Description("Usps Medium Flat Rate Box")]
checked all names and made changes

2020-10-02 09:55 UTC, DimitarChobanovSellerCloud commented on src/SellerCloud.Core/Enums/PackageType/PackageType.cs
> +        [Description("Usps Flat Rate Padded Envelope")]
checked all names and made changes

2020-10-02 09:57 UTC, stanimirsellercloud commented on src/SellerCloud.Core/Enums/PackageType/PackageType.cs
> +        [Description(@"Package/customer supplied")]
All other entries look great but this one I do not recognise. I think we should change it to `Package`.

2020-10-02 10:40 UTC, merged